// <auto-generated />
using System;
using DIG103_Ticket_platform_back.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DIG103_Ticket_platform_back.Migrations
{
    [DbContext(typeof(AppliactionDbContext))]
    [Migration("20251019023252_AddImageSupport")]
    partial class AddImageSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ArtistEvent", b =>
                {
                    b.Property<int>("ArtistsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtistsId", "EventsId");

                    b.HasIndex("EventsId");

                    b.ToTable("ArtistEvent");
                });

            modelBuilder.Entity("DIG103_Ticket_platform_back.Model.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArtistImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistImageId")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("DIG103_Ticket_platform_back.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventBackgroundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventImageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventBackgroundId")
                        .IsUnique();

                    b.HasIndex("EventImageId")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DIG103_Ticket_platform_back.Model.EventFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeatureImageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("FeatureImageId")
                        .IsUnique();

                    b.ToTable("Features");
                });

            modelBuilder.Entity("DIG103_Ticket_platform_back.Model.EventTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorPrimary")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorPrimaryLight")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorSecondary")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("DIG103_Ticket_platform_back.Model.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ArtistEvent", b =>
                {
                    b.HasOne("DIG103_Ticket_platform_back.Model.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DIG103_Ticket_platform_back.Model.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DIG103_Ticket_platform_back.Model.Artist", b =>
                {
                    b.HasOne("DIG103_Ticket_platform_back.Model.Image", "ArtistImage")
                        .WithOne()
                        .HasForeignKey("DIG103_Ticket_platform_back.Model.Artist", "ArtistImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ArtistImage");
                });

            modelBuilder.Entity("DIG103_Ticket_platform_back.Model.Event", b =>
                {
                    b.HasOne("DIG103_Ticket_platform_back.Model.Image", "EventBackground")
                        .WithOne()
                        .HasForeignKey("DIG103_Ticket_platform_back.Model.Event", "EventBackgroundId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("DIG103_Ticket_platform_back.Model.Image", "EventImage")
                        .WithOne()
                        .HasForeignKey("DIG103_Ticket_platform_back.Model.Event", "EventImageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("EventBackground");

                    b.Navigation("EventImage");
                });

            modelBuilder.Entity("DIG103_Ticket_platform_back.Model.EventFeature", b =>
                {
                    b.HasOne("DIG103_Ticket_platform_back.Model.Event", "Event")
                        .WithMany("Features")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DIG103_Ticket_platform_back.Model.Image", "FeatureImage")
                        .WithOne()
                        .HasForeignKey("DIG103_Ticket_platform_back.Model.EventFeature", "FeatureImageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("FeatureImage");
                });

            modelBuilder.Entity("DIG103_Ticket_platform_back.Model.EventTheme", b =>
                {
                    b.HasOne("DIG103_Ticket_platform_back.Model.Event", "Event")
                        .WithOne("Theme")
                        .HasForeignKey("DIG103_Ticket_platform_back.Model.EventTheme", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DIG103_Ticket_platform_back.Model.Event", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Theme")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
